version: "3"
services:
  seata-server:
    image: seataio/seata-server
    container_name: seata-server 
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      # 可选, 指定seata-server启动的IP, 该IP用于向注册中心注册时使用, 如eureka等
      SEATA_IP: 192.168.133.50
      # 可选, 指定seata-server启动的端口, 默认为 8091
      SEATA_PORT: 8091
      # 可选, 指定配置文件位置, 
      # 如 file:/root/registry, 将会加载 /root/registry.conf 作为配置文件，
      # 如果需要同时指定 file.conf文件，需要将registry.conf的config.file.name的值改为类似file:/root/file.conf：
      # 注意： 这里一定要以registry 目录结尾
      SEATA_CONFIG_NAME: file:/root/seata-config/registry
    volumes:
      - ./conf:/root/seata-config
    
